version: 2.1
jobs:
  build_and_test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t test ./ubuntu-18.04
      - run:
          name: run build tests
          command: |
            pwd;
            echo "LS .test"
            ls .test;
            docker create -v /app --name myvolumes alpine:3.4 /bin/true
            docker cp .test myvolumes:/app/.test

            docker run -it --rm \
              --volumes-from myvolumes \
              -v /app/.test:/app \
              -w /app \
              --net none \
              test bash -c 'pwd; ls; echo OK;';
            docker run -it --rm \
              --volumes-from myvolumes \
              -v /app/.test:/app \
              -w /app \
              --net none \
              test ./test.sh

workflows:
  build:
    jobs:
      - build_and_test
