aliases:
    - &deploy_environment
        working_directory: /app
        docker:
          - image: docker:17.05.0-ce-git
    - &build_and_run
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t test "${DIRECTORY}"
      - run:
          name: run build tests
          command: |
            docker create -v /app --name mycontainer alpine /bin/true
            docker cp .test/. mycontainer:/app/

            docker run -it --rm \
              --volumes-from mycontainer \
              -w /app \
              --network none \
              test ./test.sh

version: 2
workflows:
  version: 2
  build:
    jobs:
      - "Build ubuntu 18.04"
      - "Build ubuntu 16.04" # run the job twice (why not)
jobs:
    "Build ubuntu 18.04":
      <<: *deploy_environment
      environment:
        DIRECTORY: ./ubuntu-18.04
      steps: *build_and_run
    "Build ubuntu 16.04":
      <<: *deploy_environment
      environment:
        DIRECTORY: ./ubuntu-16.04
      steps: *build_and_run